CREATE TABLE PermitHolder (
PERMITHOLDERID INT NOT NULL AUTO_INCREMENT,
Name TINYTEXT NOT NULL,
Email varchar(255) NOT NULL,
PERMITNAME TINYTEXT NOT NULL,
PurchaseDate DATE NOT NULL DEFAULT CURRENT_DATE(),
VEHICLEID INT NOT NULL,
PRIMARY KEY (PERMITHOLDERID),
FOREIGN KEY (PERMITNAME) REFERENCES Permit(PERMITNAME),
FOREIGN KEY (VEHICLEID) REFERENCES Vehicle(VEHICLEID)
);

CREATE TABLE Permit(
PERMITNAME VARCHAR(255) NOT NULL,
PermitLength INT NOT NULL DEFAULT 1,
Price DECIMAL(13,2) NOT NULL,
LOTID INT NOT NULL,
PRIMARY KEY (PERMITNAME),
FOREIGN KEY (LOTID) REFERENCES Lots(LOTID)
);

CREATE TABLE Lots(
LOTID INT NOT NULL AUTO_INCREMENT,
Location VARCHAR(1000) NOT NULL,
Name TINYTEXT NOT NULL,
Capacity INT NOT NULL DEFAULT 1000,
PRIMARY KEY (LOTID)
);

CREATE TABLE Ticket(
TICKETNUMBER INT NOT NULL AUTO_INCREMENT=1000,
Violation VARCHAR(1000) NOT NULL DEFAULT 'No Permit Found',
IssueDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
PaidDate DATETIME DEFAULT NULL,
LOTID INT NOT NULL,
FineAmount DECIMAL(13,2) NOT NULL DEFAULT 75.00,
VEHICLEID INT NOT NULL,
STAFFID INT NOT NULL,
PRIMARY KEY (TICKETNUMBER),
FOREIGN KEY (VEHICLEID) REFERENCES Vehicle(VEHICLEID),
FOREIGN KEY (STAFFID) REFERENCES ParkingStaff(STAFFID),
FOREIGN KEY (LOTID) REFERENCES Lots(LOTID)
);

CREATE TABLE Vehicle(
VEHICLEID INT NOT NULL AUTO_INCREMENT=1000,
Model TINYTEXT NOT NULL,
Make TINYTEXT NOT NULL,
YEAR INT NOT NULL,
LicensePlateState TINYTEXT NOT NULL,
LicensePlateNumber TINYTEXT NOT NULL,
PRIMARY KEY (VEHICLEID)
);

CREATE TABLE ParkingStaff(
STAFFID INT NOT NULL AUTO_INCREMENT=1000,
Name TINYTEXT NOT NULL,
Email VARCHAR(255),
PRIMARY KEY(STAFFID)
);